/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class barcode_BarCode */

#ifndef _Included_barcode_BarCode
#define _Included_barcode_BarCode
#ifdef __cplusplus
extern "C" {
#endif

  JNIEXPORT void JNICALL Java_barcode_BarCode_Create(JNIEnv *, jobject, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
