/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class barcode_BarCode */

#ifndef _Included_barcode_BarCode
#define _Included_barcode_BarCode
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_barcode_BarCode_Create
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
